name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Docker image
      run: |
        docker build -t nodejs-app .

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 nodejs-app

    - name: Wait for app to start
      run: |
        for i in {1..10}; do
          curl --silent http://localhost:3000 && break
          echo "Waiting for app to start..."
          sleep 3
        done
